[target.'cfg(feature = "cargo-clippy")']
rustflags = [
  "-Wabsolute-paths-not-starting-with-crate",
  "-Wexplicit_outlives_requirements",
  "-Wmacro_use_extern_crate",
  "-Wmeta_variable_misuse",
  "-Wmissing_abi",
  "-Wmissing_docs",
  "-Wmissing_doc_code_examples",
  "-Wnoop_method_call",
  "-Wtrivial_casts",
  "-Wtrivial_numeric_casts",
  "-Wunreachable-pub",
  "-Wunused-extern-crates",
  "-Wunused-import-braces",
  "-Wunused-lifetimes",
  "-Wunused-macro-rules",
  "-Wunused-qualifications",
  "-Wunused-tuple-struct-fields",
  "-Wclippy::allow_attributes_without_reason",
  "-Wclippy::as_conversions",
  "-Wclippy::as_underscore",
  "-Wclippy::cargo_common_metadata",
  "-Wclippy::clone_on_ref_ptr",
  "-Wclippy::cognitive_complexity",
  "-Wclippy::create_dir",
  "-Wclippy::dbg_macro",
  "-Wclippy::debug_assert_with_mut_call",
  "-Wclippy::doc_markdown",
  "-Wclippy::empty_line_after_outer_attr",
  "-Wclippy::expect_used",
  "-Wclippy::fallible_impl_from",
  "-Wclippy::filetype_is_file",
  "-Wclippy::float_cmp_const",
  "-Wclippy::fn_params_excessive_bools",
  "-Wclippy::get_unwrap",
  "-Wclippy::if_then_some_else_none",
  "-Wclippy::imprecise_flops",
  "-Wclippy::let_underscore_must_use",
  "-Wclippy::lossy_float_literal",
  "-Wclippy::manual_clamp",
  "-Wclippy::multiple_inherent_impl",
  "-Wclippy::mutex_integer",
  "-Wclippy::negative_feature_names",
  "-Wclippy::nonstandard_macro_braces",
  "-Wclippy::option_option",
  "-Wclippy::panic_in_result_fn",
  "-Wclippy::path_buf_push_overwrite",
  "-Wclippy::pedantic",
  "-Wclippy::print_stderr",
  "-Wclippy::print_stdout",
  "-Wclippy::redundant_feature_names",
  "-Wclippy::rc_buffer",
  "-Wclippy::rc_mutex",
  "-Wclippy::rest_pat_in_fully_bound_structs",
  "-Wclippy::string_lit_as_bytes",
  "-Wclippy::string_to_string",
  "-Wclippy::suboptimal_flops",
  "-Wclippy::suspicious_operation_groupings",
  "-Wclippy::todo",
  "-Wclippy::trivial_regex",
  "-Wclippy::unimplemented",
  "-Wclippy::unnecessary_self_imports",
  "-Wclippy::unneeded_field_pattern",
  "-Wclippy::unreadable_literal",
  "-Wclippy::use_debug",
  "-Wclippy::use_self",
  "-Wclippy::useless_let_if_seq",
  "-Wclippy::useless_transmute",
  "-Wclippy::verbose_file_reads",
  "-Wclippy::wildcard_dependencies",
]
